export const CATEGORIES = [
  { id: 'tudo', label: 'Tudo', icon: '🛒' },
  { id: 'novos', label: 'Novos', icon: '🆕' },
  { id: 'achados', label: 'Achados', icon: '🔍' },
  { id: 'homem', label: 'Homem', icon: '👔' },
  { id: 'mulher', label: 'Mulher', icon: '👗' },
  { id: 'calcados', label: 'Calçados', icon: '👟' },
  { id: 'cozinha', label: 'Cozinha', icon: '🍳' },
  { id: 'tech', label: 'Tech', icon: '💻' },
  { id: 'casa', label: 'Casa', icon: '🏠' },
  { id: 'ferramentas', label: 'Ferramentas', icon: '🛠️' },
  { id: 'beleza', label: 'Beleza', icon: '💄' },
  { id: 'pets', label: 'Pets', icon: '🐶' },
  { id: 'suplementos', label: 'Suplementos', icon: '💊' },
  { id: 'livros', label: 'Livros', icon: '📚' },
  { id: 'escolar', label: 'Escolar', icon: '✏️' },
  { id: 'alimentos', label: 'Alimentos e Bebidas', icon: '🍔' },
  { id: 'automotivo', label: 'Automotivo', icon: '🚗' },
  { id: 'bebes', label: 'Bebês', icon: '🍼' },
  { id: 'cuidados', label: 'Cuidados Pessoais', icon: '🧼' },
  { id: 'bolsas', label: 'Bolsas e Mochilas', icon: '🎒' },
  { id: 'brinquedos', label: 'Brinquedos e Jogos', icon: '🧸' },
  { id: 'jardim', label: 'Casa, Jardim e Limpeza', icon: '🧹' },
  { id: 'celulares', label: 'Celulares e Comunicação', icon: '📱' },
  { id: 'informatica', label: 'Computadores e Informática', icon: '🖥️' },
  { id: 'eletronicos', label: 'Eletrônicos, TV e Áudio', icon: '📺' },
  { id: 'esportes', label: 'Esportes e Lazer', icon: '⚽' },
  { id: 'filmes', label: 'Filmes, Séries e Música', icon: '🎬' },
  { id: 'games', label: 'Games e Consoles', icon: '🎮' },
  { id: 'papelaria', label: 'Papelaria e Escritório', icon: '📎' },
  { id: 'roupas', label: 'Roupas e Acessórios', icon: '👕' },
];